### ISSUE TITLE
I would like to ask about the paper on code correspondence 

### ISSUE THREAD

**Issue by chenzhaoxingxin** [SIKtt/Fast-Seeping-Eikonal#1]
Dear author:
Hello, thank you very much for publishing the code to help us learn. The example in your code is very effective. I would like to learn about discontinuous finite element knowledge based on the code. So, I would like to ask you, what equation does your code solve for? Is there any relevant article that can help us understand?
Thank you for taking the time to check my information. I wish you good health and smooth work. Looking forward to your reply!

**Comment by SIKtt** [comment]
It based on Fast sweeping Method for Eikonal equation[(Zhao, 2005)](https://doi.org/10.1090/S0025-5718-04-01678-3) and a simplifed DG Method refer to [(Li & Shu, 2007)](http://dx.doi.org/10.1016/j.jcp.2008.05.018).

**Comment by chenzhaoxingxin** [comment]
Thank you for your reply!
    I have read the article (Li & Shu, 2007), which uses the Fast sweeping Method to obtain the initial solution, and then uses the DG method to further solve it. But his grid is a rectangular grid, and your grid uses a triangular grid, right? On the basis of the triangular mesh, first use the Fast sweeping Method to obtain the initial solution, and then use the DG method to further obtain the travel time solution, right?

**Comment by SIKtt** [comment]
The method you mentioned above might be a good way to get the solution. If you are interested in getting Traveltime in Tri-mesh [Luo, 2007](https://doi.org/10.1137/050627083) with DG realization, I recommend with related work of Shu(Semi-Discretization).

**Comment by chenzhaoxingxin** [comment]
Sorry, I didn't quite understand what you meant. You mentioned the a simplifed DG Method in your previous email. That's why I want to confirm if you used the DG method when solving eikonal?

**Comment by SIKtt** [comment]
Both scripts in this repo used FD solver.

**Comment by chenzhaoxingxin** [comment]
Thank you for your reply. I encountered this issue while running the code. I'm not sure if you have encountered it before, and how can I solve it?
![image](https://user-images.githubusercontent.com/50125253/236626945-1c9e4866-cf95-4705-90ca-672c26331e22.png)

**Comment by SIKtt** [comment]
Using its ``data`` and ``type`` property instead of casting ``CellBlock`` object to ``List``.

**Comment by SIKtt** [comment]
[cannot unpack non-iterable CellBlock object](https://github.com/nschloe/meshio/issues/1307)
```
cellList = np.array(mesh.cells[1].data)
```

**Comment by chenzhaoxingxin** [comment]
Thanks! I would also like to ask that for rectangular grids, the fast scanning method is relatively easy to achieve by scanning in different directions. It is quite difficult to scan unstructured meshes such as triangular meshes. How do you sort triangular meshes and then scan them? Is there any relevant paper that can help understand?

**Comment by SIKtt** [comment]
According to Luo(2007), cells can be sorted by its distance from reference points. This script just calc its distance in time. And you can storage distance in Heap to get a better performance.

**Comment by chenzhaoxingxin** [comment]
Thank you very much. I will go and read the relevant papers.
